version: '3.8'

services:
  # Main application
  trading-bot:
    build: .
    container_name: trading-bot-app
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://botuser:botpassword@postgres:5432/trading_bot_db
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - config/.env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - trading-bot-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: trading-bot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: trading_bot_db
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: botpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/postgres.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    networks:
      - trading-bot-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: trading-bot-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - trading-bot-network

  # Optional: Web Dashboard (Future)
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: trading-bot-dashboard
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - API_URL=http://trading-bot:8000
    networks:
      - trading-bot-network
    profiles:
      - dashboard

  # Optional: Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: trading-bot-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - dashboard
    networks:
      - trading-bot-network
    profiles:
      - dashboard

volumes:
  postgres_data:
  redis_data:

networks:
  trading-bot-network:
    driver: bridge
